[2024-01-18 20:15:14,707] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_Futbol.conexion_BD scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-18 20:15:14,725] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_Futbol.conexion_BD scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-18 20:15:14,725] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-18 20:15:14,726] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-01-18 20:15:14,759] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-18 20:15:14,866] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conexion_BD> on 2024-01-17 00:00:00+00:00
[2024-01-18 20:15:14,875] {standard_task_runner.py:52} INFO - Started process 22658 to run task
[2024-01-18 20:15:14,884] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Futbol', 'conexion_BD', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '1247', '--raw', '--subdir', 'DAGS_FOLDER/ETLSachetto.py', '--cfg-path', '/tmp/tmp5k9w310x', '--error-file', '/tmp/tmprsc04blj']
[2024-01-18 20:15:14,886] {standard_task_runner.py:80} INFO - Job 1247: Subtask conexion_BD
[2024-01-18 20:15:15,309] {task_command.py:371} INFO - Running <TaskInstance: ETL_Futbol.conexion_BD scheduled__2024-01-17T00:00:00+00:00 [running]> on host 8278623e2516
[2024-01-18 20:15:15,624] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-01-18 20:15:16,211] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ignacio Sachetto
AIRFLOW_CTX_DAG_ID=ETL_Futbol
AIRFLOW_CTX_TASK_ID=conexion_BD
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-01-18 20:15:16,215] {ETLSachetto.py:43} INFO - Conectandose a la BD en la fecha: 2024-01-17 0
[2024-01-18 20:15:20,161] {ETLSachetto.py:51} INFO - Connected to Redshift successfully!
[2024-01-18 20:15:20,162] {python.py:173} INFO - Done. Returned value was: None
[2024-01-18 20:15:20,187] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_Futbol, task_id=conexion_BD, execution_date=20240117T000000, start_date=20240118T201514, end_date=20240118T201520
[2024-01-18 20:15:20,450] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-18 20:15:20,673] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-01-18 20:16:42,483] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_Futbol.conexion_BD scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-18 20:16:42,500] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_Futbol.conexion_BD scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-18 20:16:42,501] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-18 20:16:42,501] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-01-18 20:16:42,502] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-18 20:16:42,586] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conexion_BD> on 2024-01-17 00:00:00+00:00
[2024-01-18 20:16:42,593] {standard_task_runner.py:52} INFO - Started process 22771 to run task
[2024-01-18 20:16:42,606] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Futbol', 'conexion_BD', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '1253', '--raw', '--subdir', 'DAGS_FOLDER/ETLSachetto.py', '--cfg-path', '/tmp/tmpx_8ecaim', '--error-file', '/tmp/tmpqziaikjv']
[2024-01-18 20:16:42,612] {standard_task_runner.py:80} INFO - Job 1253: Subtask conexion_BD
[2024-01-18 20:16:42,833] {task_command.py:371} INFO - Running <TaskInstance: ETL_Futbol.conexion_BD scheduled__2024-01-17T00:00:00+00:00 [running]> on host 8278623e2516
[2024-01-18 20:16:43,101] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-01-18 20:16:43,296] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ignacio Sachetto
AIRFLOW_CTX_DAG_ID=ETL_Futbol
AIRFLOW_CTX_TASK_ID=conexion_BD
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-01-18 20:16:43,297] {ETLSachetto.py:39} INFO - Conectandose a la BD en la fecha: 2024-01-17 0
[2024-01-18 20:16:44,723] {ETLSachetto.py:47} INFO - Connected to Redshift successfully!
[2024-01-18 20:16:44,724] {python.py:173} INFO - Done. Returned value was: None
[2024-01-18 20:16:44,751] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_Futbol, task_id=conexion_BD, execution_date=20240117T000000, start_date=20240118T201642, end_date=20240118T201644
[2024-01-18 20:16:44,832] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-18 20:16:44,955] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
