[2024-01-17 00:30:51,014] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:30:42.297143+00:00 [queued]>
[2024-01-17 00:30:51,030] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:30:42.297143+00:00 [queued]>
[2024-01-17 00:30:51,031] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:30:51,032] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-01-17 00:30:51,032] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:30:51,084] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conectar_redshift> on 2024-01-17 00:30:42.297143+00:00
[2024-01-17 00:30:51,089] {standard_task_runner.py:52} INFO - Started process 5750 to run task
[2024-01-17 00:30:51,093] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_redshift', 'conectar_redshift', 'manual__2024-01-17T00:30:42.297143+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/ETLSachetto.py', '--cfg-path', '/tmp/tmpiwew3kyn', '--error-file', '/tmp/tmphkdk78sz']
[2024-01-17 00:30:51,095] {standard_task_runner.py:80} INFO - Job 157: Subtask conectar_redshift
[2024-01-17 00:30:51,241] {task_command.py:371} INFO - Running <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:30:42.297143+00:00 [running]> on host 8278623e2516
[2024-01-17 00:30:51,614] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=NachoSachetto
AIRFLOW_CTX_DAG_ID=dag_redshift
AIRFLOW_CTX_TASK_ID=conectar_redshift
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:30:42.297143+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-17T00:30:42.297143+00:00
[2024-01-17 00:30:53,105] {python.py:173} INFO - Done. Returned value was: (<connection object at 0x7f105082f2f0; dsn: 'user=nachosachetto1998_coderhouse password=xxx dbname=data-engineer-database host=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com port=5439', closed: 0>, <cursor object at 0x7f105087ec50; closed: 0>)
[2024-01-17 00:30:53,118] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-01-17 00:30:53,119] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type connection is not JSON serializable
[2024-01-17 00:30:53,136] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_redshift, task_id=conectar_redshift, execution_date=20240117T003042, start_date=20240117T003051, end_date=20240117T003053
[2024-01-17 00:30:53,229] {standard_task_runner.py:97} ERROR - Failed to execute job 157 for task conectar_redshift (Object of type connection is not JSON serializable; 5750)
[2024-01-17 00:30:53,277] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-17 00:30:53,372] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
