[2024-01-17 00:49:09,303] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:44:35.216651+00:00 [None]>
[2024-01-17 00:49:14,686] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:44:35.216651+00:00 [None]>
[2024-01-17 00:49:14,855] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:49:14,954] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-01-17 00:49:14,954] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:49:18,098] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conectar_redshift> on 2024-01-17 00:44:35.216651+00:00
[2024-01-17 00:49:18,344] {standard_task_runner.py:52} INFO - Started process 6613 to run task
[2024-01-17 00:49:19,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_redshift', 'conectar_redshift', 'manual__2024-01-17T00:44:35.216651+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/ETLSachetto.py', '--cfg-path', '/tmp/tmp51hxmlt7', '--error-file', '/tmp/tmppzyxq416']
[2024-01-17 00:49:19,572] {standard_task_runner.py:80} INFO - Job 183: Subtask conectar_redshift
[2024-01-17 00:49:25,585] {task_command.py:371} INFO - Running <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:44:35.216651+00:00 [running]> on host 8278623e2516
[2024-01-17 00:49:27,483] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=NachoSachetto
AIRFLOW_CTX_DAG_ID=dag_redshift
AIRFLOW_CTX_TASK_ID=conectar_redshift
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:44:35.216651+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-17T00:44:35.216651+00:00
[2024-01-17 00:49:33,262] {python.py:173} INFO - Done. Returned value was: (<connection object at 0x7f10508292f0; dsn: 'user=nachosachetto1998_coderhouse password=xxx dbname=data-engineer-database host=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com port=5439', closed: 0>, <cursor object at 0x7f105087cc50; closed: 0>)
[2024-01-17 00:49:34,020] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-01-17 00:49:34,214] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type connection is not JSON serializable
[2024-01-17 00:49:34,645] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_redshift, task_id=conectar_redshift, execution_date=20240117T004435, start_date=20240117T004909, end_date=20240117T004934
[2024-01-17 00:49:35,206] {standard_task_runner.py:97} ERROR - Failed to execute job 183 for task conectar_redshift (Object of type connection is not JSON serializable; 6613)
[2024-01-17 00:49:35,411] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-17 00:49:37,698] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
