[2024-01-17 00:41:54,828] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:41:42.843261+00:00 [queued]>
[2024-01-17 00:41:54,846] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:41:42.843261+00:00 [queued]>
[2024-01-17 00:41:54,846] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:41:54,848] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-01-17 00:41:54,848] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:41:54,922] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conectar_redshift> on 2024-01-17 00:41:42.843261+00:00
[2024-01-17 00:41:54,953] {standard_task_runner.py:52} INFO - Started process 6358 to run task
[2024-01-17 00:41:54,958] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_redshift', 'conectar_redshift', 'manual__2024-01-17T00:41:42.843261+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/ETLSachetto.py', '--cfg-path', '/tmp/tmpzg5wryk8', '--error-file', '/tmp/tmp0wzln0p_']
[2024-01-17 00:41:54,960] {standard_task_runner.py:80} INFO - Job 166: Subtask conectar_redshift
[2024-01-17 00:41:55,161] {task_command.py:371} INFO - Running <TaskInstance: dag_redshift.conectar_redshift manual__2024-01-17T00:41:42.843261+00:00 [running]> on host 8278623e2516
[2024-01-17 00:41:55,548] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=NachoSachetto
AIRFLOW_CTX_DAG_ID=dag_redshift
AIRFLOW_CTX_TASK_ID=conectar_redshift
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:41:42.843261+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-17T00:41:42.843261+00:00
[2024-01-17 00:41:56,917] {python.py:173} INFO - Done. Returned value was: (<connection object at 0x7f10506f9ad0; dsn: 'user=nachosachetto1998_coderhouse password=xxx dbname=data-engineer-database host=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com port=5439', closed: 0>, <cursor object at 0x7f105087dc50; closed: 0>)
[2024-01-17 00:41:56,928] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-01-17 00:41:56,929] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type connection is not JSON serializable
[2024-01-17 00:41:56,945] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_redshift, task_id=conectar_redshift, execution_date=20240117T004142, start_date=20240117T004154, end_date=20240117T004156
[2024-01-17 00:41:57,026] {standard_task_runner.py:97} ERROR - Failed to execute job 166 for task conectar_redshift (Object of type connection is not JSON serializable; 6358)
[2024-01-17 00:41:57,069] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-17 00:41:57,169] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
